packetbeat.protocols.dns:
  ports: [53]

  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 8080, 8081, 5000, 8002]

packetbeat.protocols.mysql:
  ports: [3306]

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["logstash:5044"]
