version: '2'

services:
# Ressie MySql
  ressie_operational_db:
    restart: always
    build: database/
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - ./database/sql/:/docker-entrypoint-initdb.d
    env_file:
        - variables.env

#Elastic stack
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
      - "5044:5044"
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

# App Databases
  mysql:
    restart: always
    build: apps/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./apps/mysql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    env_file:
        - variables.env

  php:
    build: apps/php
    restart: always
    working_dir: /project
    ports:
      - "9090:80"
      - "443:443"
    volumes:
      - ./apps/php/application:/project
    depends_on:
      - mysql
    links:
      - logstash
    env_file:
      - variables.env
volumes:
  mysql:
    driver: local